PRGS =  baseml codeml basemlg mcmctree pamp evolver yn00 chi2 
CC = cl # cc, gcc, cl
CFLAGS =  -O2 -Ot 

DEFINE = #
LIBS = #-lm -lM

all : $(PRGS)
 
baseml : baseml.c  tools.c treesub.c treespace.c paml.h 
  $(CC) $(CFLAGS) baseml.c tools.c $(LIBS)
basemlg : basemlg.c  tools.c treesub.c treespace.c paml.h 
  $(CC) $(CFLAGS) basemlg.c tools.c $(LIBS)
codeml : codeml.c  tools.c treesub.c treespace.c paml.h 
  $(CC) $(CFLAGS) codeml.c tools.c $(LIBS)
evolver : evolver.c  tools.c treesub.c treespace.c paml.h 
  $(CC) $(CFLAGS) evolver.c tools.c $(LIBS)
mcmctree : mcmctree.c  tools.c treesub.c treespace.c paml.h 
  $(CC) $(CFLAGS) mcmctree.c tools.c $(LIBS)
  $(CC) $(CFLAGS) -Feinfinitesites.exe -D INFINITESITES mcmctree.c tools.c $(LIBS)
pamp : pamp.c  tools.c treesub.c treespace.c paml.h 
  $(CC) $(CFLAGS) pamp.c tools.c $(LIBS)
yn00 : yn00.c tools.c
  $(CC) $(CFLAGS) yn00.c tools.c $(LIBS)
chi2 : chi2.c
  $(CC) $(CFLAGS) chi2.c $(LIBS)
